PWN-7066 - Try to fix blur mask effect
p2p-org/key-app-android pull request #1201
Opened 2023-02-02 14:44 UTC by Davran331122

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-7066

2023-02-02 15:00 UTC, kabramovp2p approved these changes

2023-02-02 15:42 UTC, gslevinkov approved these changes

2023-02-03 04:58 UTC, NikolaiEmelianov requested changes

2023-02-03 04:58 UTC, NikolaiEmelianov commented on app/src/main/AndroidManifest.xml
> +            android:hardwareAccelerated="false"
are you sure to disable it for whole app?

2023-02-03 04:58 UTC, NikolaiEmelianov commented on app/src/main/AndroidManifest.xml
> +            android:hardwareAccelerated="false"
https://developer.android.com/topic/performance/hardware-accel#view-level
maybe only for view?

2023-02-03 21:28 UTC, NikolaiEmelianov approved these changes

2023-02-06 07:41 UTC, merged