PWN-7020 - jupiter tokens request
p2p-org/key-app-android pull request #1204
Opened 2023-02-03 07:08 UTC by NikolaiEmelianov

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-7020

## Description of Work

jupiter tokens request

2023-02-03 07:27 UTC, gslevinkov approved these changes

2023-02-03 07:27 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterToken.kt
> +data class JupiterToken(
we can remove implementation detail - Jupiter and call it just SwapToken? 
just a nitpick

2023-02-03 07:27 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterToken.kt
> +    val extensions: JupiterTokenExtensions,
domain models can't have entities with @SerializedName inside

2023-02-03 07:27 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterToken.kt
> +    val address: String,
if it's mint - it's Base58String

2023-02-03 07:27 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterToken.kt
> +    val logoURI: String,
logoUri

2023-02-03 08:51 UTC, kabramovp2p approved these changes

2023-02-03 09:05 UTC, 1sakov requested changes

2023-02-03 09:05 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTokenRepository.kt
> +    private fun List<JupiterTokenResponse>.toJupiterToken(): List<SwapToken> = map { respons ->
move mappings to a separate mapper

2023-02-03 09:05 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTokenRepository.kt
> +        withContext(dispatchers.io) {
this context is redundant

2023-02-03 09:05 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/SwapToken.kt
> +    val tags: List<String>
Are you sure we don't have `SwapToken` anymore in the project?
Seems to me that this is a conflict name. 

Let's name it `JupiterSwapToken` please

2023-02-03 09:05 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/SwapTokenExtensions.kt
> +)
This class is redundant.
Use `coingeckoId` directly in `SwapToken`

2023-02-03 09:06 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTokenRepository.kt
> +) : SwapTokensRepository {
Why? This repository is getting us SwapTokens - that's all we need
The place where we getting this tokens - is implementation detail, look at the TokenPricesRepository, seems great

2023-02-03 09:19 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTokenRepository.kt
> +) : SwapTokensRepository {
The implementation of each swap is too different. 
You will not be able to make as in TokenPrices. 

Orca is absolutely different, Serum swap is different. 
Jupiter has its own implementation.

It's better to know what exactly repository and swap you are using. 
I don't think this pattern of naming is correct here. 
Let's name it with full context.

Mb `JupiterTokensRepository` is better

2023-02-06 08:08 UTC, 1sakov approved these changes

2023-02-06 08:08 UTC, merged