PWN-5418 - Implement Proto Data Store
p2p-org/key-app-android pull request #1238
Opened 2023-02-12 09:58 UTC by Davran331122

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-5418

2023-02-12 10:01 UTC, Davran331122 commented on core/build.gradle
> +    api 'org.bitcoinj:bitcoinj-core:0.16.2'
I Updated bitcoin library, cause it's used old Protobuf version, and we had conflicts via merge them.

2023-02-13 08:37 UTC, gslevinkov requested changes

2023-02-13 08:37 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/infrastructure/proto/serializer/TokenKeysDataStore.kt
> +class TokenKeysDataStoreSerializer(
TokenKeysDataStore

2023-02-13 08:37 UTC, gslevinkov commented on app/build.gradle
> +    id "com.google.protobuf" version "0.8.17"
don't forget to add
```
-keepclassmembers class * extends androidx.datastore.preferences.protobuf.GeneratedMessageLite {
    <fields>;
}
```

2023-02-13 08:37 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/infrastructure/proto/serializer/TokenKeysDataStore.kt
> +class TokenKeysDataStoreSerializer(
and what is token keys anyway? it is public + private keys? it's Account / Wallets DataStore then

2023-02-13 08:37 UTC, gslevinkov commented on app/src/main/proto/token_keys_data_store.proto
> +  string public_key = 1;
encrypted_public_key
encrypted_private_key

can we make private_key into string too?

2023-02-13 08:37 UTC, gslevinkov commented on app/src/main/proto/torus_data_store.proto
> +  DeviceShare custom_third_share = 5;
please use `optional` or `required` modifiers

2023-02-14 08:58 UTC, kabramovp2p approved these changes

2023-05-15 12:52 UTC, closed without merging