PWN-7614 send feature to ui relay, send action
p2p-org/key-app-android pull request #1476
Opened 2023-03-22 10:57 UTC by NikolaiEmelianov

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-7614

## Description of Work

send feature to ui relay, send action

2023-03-22 15:10 UTC, Davran331122 commented on app/src/main/java/org/p2p/wallet/newsend/ui/confirmsend/SendBridgeSendAction.kt
> +    private fun sendTransaction(state: SendState.Static.ReadyToSend, view: NewSendContract.View) {
Can we detach view from this class ?

2023-03-22 15:10 UTC, Davran331122 commented on app/src/main/java/org/p2p/wallet/newsend/ui/confirmsend/SendBridgeSendAction.kt
> +    private fun sendTransaction(state: SendState.Static.ReadyToSend, view: NewSendContract.View) {
just pass event for sendTransaction

2023-03-23 08:27 UTC, kabramovp2p approved these changes

2023-03-23 08:48 UTC, kabramovp2p approved these changes

2023-03-23 09:38 UTC, 1sakov commented
Being honestly, it looks not so good. 
Let's postpone the idea of common send state machine

Make send only for Bridges please 
@NikolaiEmelianov

2023-03-23 09:38 UTC, 1sakov requested changes

2023-03-28 08:30 UTC, closed without merging