PWN-8222 - Fix token sorting on main screen before PTR
p2p-org/key-app-android pull request #1630
Opened 2023-04-25 13:51 UTC by Davran331122

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-8222

2023-04-25 13:53 UTC, gslevinkov approved these changes

2023-04-26 06:38 UTC, eduardmaximovich approved these changes

2023-04-26 11:44 UTC, 1sakov requested changes

2023-04-26 11:44 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
> +        }.sortedWith(TokenComparator())
We are sorting before saving into DB. 
Are you sure the `map` here breaks the sorting?

2023-04-28 09:20 UTC, merged